# Generated by Django 4.2 on 2025-06-12 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره درخواست')),
                ('document_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره سند')),
                ('package_count', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='تعداد بسته')),
                ('courier_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام پیک')),
                ('visitor_name', models.CharField(max_length=100, verbose_name='نام ویزیتور')),
                ('customer_name', models.CharField(max_length=100, verbose_name='نام مشتری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('payment_term', models.CharField(choices=[('cash', 'نقدی'), ('1m', '1 ماهه'), ('2m', '2 ماهه'), ('3m', '3 ماهه'), ('4m', '4 ماهه')], max_length=10, verbose_name='شرایط تسویه')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('warehouse', 'ارسال شده به انبار'), ('ready', 'آماده تحویل'), ('delivered', 'تحویل داده شده'), ('parent', 'تفکیک شده به انبارها'), ('completed', 'نهایی شده'), ('backorder', 'در انتظار موجودی'), ('waiting_for_customer_shipment', 'در انتظار ارسال به مشتری'), ('sent_to_warehouse', ' ارسال شده به انبار از بک اوردر')], default='pending', max_length=30, verbose_name='وضعیت سفارش')),
                ('is_sub_order', models.BooleanField(default=False, verbose_name='آیا زیرسفارش است؟ (قدیمی)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.order', verbose_name='سفارش مادر (قدیمی)')),
                ('parent_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_orders', to='products.order', verbose_name='سفارش والد (جدید)')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام انبار')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse', to=settings.AUTH_USER_MODEL, verbose_name='کاربر انباردار')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(max_length=20, unique=True, verbose_name='شماره ارسالی')),
                ('shipment_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('courier_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام پیک')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات ارسال')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='products.order', verbose_name='سفارش مرتبط')),
            ],
            options={
                'verbose_name': 'ارسالی',
                'verbose_name_plural': 'ارسالی\u200cها',
                'ordering': ['-shipment_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='برند')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد کالا')),
                ('name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('car_group', models.CharField(default='عمومی', max_length=100, verbose_name='گروه خودرو')),
                ('price', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='قیمت')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('max_payment_term', models.CharField(blank=True, choices=[('cash', 'نقدی'), ('1m', '1 ماهه'), ('2m', '2 ماهه'), ('3m', '3 ماهه'), ('4m', '4 ماهه')], max_length=10, null=True, verbose_name='حداکثر مهلت تسویه')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.warehouse', verbose_name='انبار')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('warehouse', 'ارسال شده به انبار'), ('ready', 'آماده تحویل'), ('delivered', 'تحویل داده شده'), ('parent', 'تفکیک شده به انبارها'), ('completed', 'نهایی شده'), ('backorder', 'در انتظار موجودی'), ('waiting_for_customer_shipment', 'در انتظار ارسال به مشتری'), ('sent_to_warehouse', ' ارسال شده به انبار از بک اوردر')], max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='products.order')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.IntegerField(blank=True, null=True, verbose_name='تعداد درخواستی')),
                ('allocated_quantity', models.IntegerField(default=0, verbose_name='تعداد تخصیص یافته')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True, verbose_name='قیمت')),
                ('payment_term', models.CharField(choices=[('cash', 'نقدی'), ('1m', '1 ماهه'), ('2m', '2 ماهه'), ('3m', '3 ماهه'), ('4m', '4 ماهه')], default='cash', max_length=50, verbose_name='شرایط پرداخت')),
                ('warehouse_status', models.CharField(choices=[('pending', 'در انتظار تایید انبار'), ('confirmed', 'تایید شده توسط انبار'), ('ready', 'آماده ارسال'), ('out_of_stock', 'ناموجود'), ('backorder', 'در انتظار موجودی'), ('pending_supply', 'در انتظار تامین موجودی'), ('waiting_for_warehouse_confirmation', 'در انتظار تایید انباردار')], default='pending', max_length=100, verbose_name='وضعیت انبار')),
                ('warehouse_note', models.TextField(blank=True, null=True, verbose_name='یادداشت انبار')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
        migrations.CreateModel(
            name='DocumentNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='شماره سند')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_number_obj', to='products.orderitem', verbose_name='آیتم سفارش')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_numbers', to='products.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'شماره سند',
                'verbose_name_plural': 'شماره سندها',
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('store_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام فروشگاه')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن ثابت')),
                ('mobile', models.CharField(error_messages={'unique': 'مشتری دیگری با این شماره همراه قبلاً ثبت شده است.'}, max_length=20, unique=True, verbose_name='شماره موبایل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مرتبط')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('document_number__isnull', False), models.Q(('document_number', ''), _negated=True)), fields=('document_number',), name='unique_document_number'),
        ),
        migrations.AlterUniqueTogether(
            name='documentnumber',
            unique_together={('warehouse', 'number')},
        ),
    ]
