# Generated by Django 4.2 on 2025-06-12 17:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-shipment_date'], 'verbose_name': 'ارسال', 'verbose_name_plural': 'ارسال\u200cها'},
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_backorder',
            field=models.BooleanField(default=False, verbose_name='ارسال بک\u200cاوردر'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='courier_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='نام پیک'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='شماره ارسال'),
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_shipped', models.PositiveIntegerField(verbose_name='تعداد ارسال شده')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.orderitem')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.shipment')),
            ],
            options={
                'verbose_name': 'قلم ارسالی',
                'verbose_name_plural': 'اقلام ارسالی',
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='items',
            field=models.ManyToManyField(related_name='shipments', through='products.ShipmentItem', to='products.orderitem'),
        ),
    ]
