# Generated by Django 4.2 on 2025-06-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_shipment_options_shipment_is_backorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('in_transit', 'در حال ارسال'), ('delivered', 'تحویل داده شده')], default='pending', max_length=50, verbose_name='وضعیت ارسال'),
        ),
    ]
