# Generated by Django 4.2 on 2025-06-18 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_shipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='parent_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_shipments', to='products.order', verbose_name='سفارش اصلی'),
        ),
        migrations.AlterUniqueTogether(
            name='shipmentitem',
            unique_together={('shipment', 'order_item')},
        ),
    ]
