# Generated by Django 5.2.4 on 2025-09-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_order_status_alter_orderstatushistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivered_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد تحویل شده'),
        ),
    ]
