# Generated by Django 4.2 on 2025-06-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_shipment_parent_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='sub_orders',
            field=models.ManyToManyField(blank=True, related_name='included_in_shipments', to='products.order', verbose_name='زیرسفارش\u200cهای شامل شده'),
        ),
    ]
