# Generated by Django 4.2 on 2025-06-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_shipment_sub_orders'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(fields=('order',), name='unique_order_shipment'),
        ),
    ]
