# Generated by Django 5.2.4 on 2025-09-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'سبد خرید'), ('pending', 'در انتظار تأیید'), ('warehouse', 'ارسال شده به انبار'), ('ready', 'آماده تحویل'), ('delivered', 'تحویل داده شده'), ('parent', 'تفکیک شده به انبارها'), ('completed', 'نهایی شده'), ('backorder', 'در انتظار موجودی'), ('waiting_for_customer_shipment', 'در انتظار ارسال به مشتری'), ('sent_to_warehouse', ' ارسال شده به انبار از بک اوردر'), ('waiting_for_warehouse_confirmation', 'در انتظار تایید انباردار'), ('shipped', 'ارسال شده')], default='pending', max_length=100, verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('cart', 'سبد خرید'), ('pending', 'در انتظار تأیید'), ('warehouse', 'ارسال شده به انبار'), ('ready', 'آماده تحویل'), ('delivered', 'تحویل داده شده'), ('parent', 'تفکیک شده به انبارها'), ('completed', 'نهایی شده'), ('backorder', 'در انتظار موجودی'), ('waiting_for_customer_shipment', 'در انتظار ارسال به مشتری'), ('sent_to_warehouse', ' ارسال شده به انبار از بک اوردر'), ('waiting_for_warehouse_confirmation', 'در انتظار تایید انباردار'), ('shipped', 'ارسال شده')], max_length=50),
        ),
    ]
