# Generated by Django 5.2.4 on 2025-09-20 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_order_status_alter_orderstatushistory_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام پیک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'پیک',
                'verbose_name_plural': 'پیک\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='courier_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام پیک (منسوخ شده)'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='courier_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام پیک (منسوخ شده)'),
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.courier', verbose_name='پیک'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.courier', verbose_name='پیک'),
        ),
    ]
