# Generated by Django 5.2.4 on 2025-09-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_courier_alter_order_courier_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('shipped', 'ارسال شده'), ('in_transit', 'در حال ارسال'), ('delivered', 'تحویل داده شده')], default='pending', max_length=50, verbose_name='وضعیت ارسال'),
        ),
    ]
