# Generated by Django 4.2 on 2025-06-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_order_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره سند'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='شماره درخواست'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تأیید'), ('warehouse', 'ارسال شده به انبار'), ('ready', 'آماده تحویل'), ('delivered', 'تحویل داده شده'), ('parent', 'تفکیک شده به انبارها'), ('completed', 'نهایی شده'), ('backorder', 'در انتظار موجودی'), ('waiting_for_customer_shipment', 'در انتظار ارسال به مشتری'), ('sent_to_warehouse', ' ارسال شده به انبار از بک اوردر'), ('waiting_for_warehouse_confirmation', 'در انتظار تایید انباردار')], default='pending', max_length=100, verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تأیید'), ('warehouse', 'ارسال شده به انبار'), ('ready', 'آماده تحویل'), ('delivered', 'تحویل داده شده'), ('parent', 'تفکیک شده به انبارها'), ('completed', 'نهایی شده'), ('backorder', 'در انتظار موجودی'), ('waiting_for_customer_shipment', 'در انتظار ارسال به مشتری'), ('sent_to_warehouse', ' ارسال شده به انبار از بک اوردر'), ('waiting_for_warehouse_confirmation', 'در انتظار تایید انباردار')], max_length=50),
        ),
    ]
