# Generated by Django 5.2.4 on 2025-10-09 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_shipment_delivery_date_alter_shipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account',
            field=models.OneToOneField(help_text='حساب دفتر کل که این حساب بانکی به آن متصل است (مثل: 112001 - بانک ملی)', on_delete=django.db.models.deletion.PROTECT, to='products.account', verbose_name='حساب مرتبط'),
        ),
    ]
