# Generated by Django 5.2.4 on 2025-10-13 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_bankaccount_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSettlementDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payments_data', models.JSONField(default=list, help_text='لیست تمام پرداخت\u200cهای ثبت شده', verbose_name='اطلاعات پرداخت\u200cها')),
                ('customer_payments_data', models.JSONField(default=dict, help_text='اطلاعات پرداخت\u200cهای مشتریان برای هر سطر', verbose_name='اطلاعات پرداخت به مشتریان')),
                ('invoice_settlements_data', models.JSONField(default=dict, help_text='اطلاعات تسویه فاکتورها برای هر سطر', verbose_name='اطلاعات تسویه فاکتورها')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('finalized', 'نهایی شده'), ('cancelled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
                ('session_id', models.CharField(help_text='شناسه یکتا برای این draft', max_length=100, unique=True, verbose_name='شناسه نشست')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_settlement_drafts', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.customer', verbose_name='مشتری')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_settlement_drafts', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش کننده')),
            ],
            options={
                'verbose_name': 'پیش\u200cنویس تسویه فاکتور',
                'verbose_name_plural': 'پیش\u200cنویس\u200cهای تسویه فاکتور',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['-updated_at'], name='products_in_updated_adfd58_idx'), models.Index(fields=['status'], name='products_in_status_0dabe1_idx'), models.Index(fields=['session_id'], name='products_in_session_88d46d_idx')],
            },
        ),
    ]
