# Generated by Django 4.2 on 2025-06-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام مشتری'),
        ),
        migrations.AddField(
            model_name='notification',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره سفارش'),
        ),
        migrations.AddField(
            model_name='notification',
            name='product_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام کالا'),
        ),
    ]
