# Generated by Django 5.2.4 on 2025-10-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_invoicesettlementdraft'),
        ('products', '0011_add_work_date_to_settlement_draft'),
    ]

    operations = [
    ]
