# Generated by Django 5.2.7 on 2025-10-20 13:45

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_merge_20251013_1043'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoicesettlementdraft',
            name='products_in_updated_adfd58_idx',
        ),
        migrations.RenameIndex(
            model_name='invoicesettlementdraft',
            new_name='products_in_work_da_78ba55_idx',
            old_name='products_in_work_da_idx',
        ),
        migrations.RenameIndex(
            model_name='invoicesettlementdraft',
            new_name='products_in_work_da_a86f75_idx',
            old_name='products_in_work_st_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='price_with_vat',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='فقط برای محصولات گروه ۴ (ایساکو)', max_digits=100, null=True, verbose_name='قیمت با ارزش افزوده'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.CharField(choices=[('group_1', 'گروه ۱ - حداکثر ۴ ماهه با تخفیف تدریجی'), ('group_2', 'گروه ۲ - فقط نقدی بدون تخفیف'), ('group_3', 'گروه ۳ - حداکثر ۲ ماهه با تخفیف نقدی'), ('group_4', 'گروه ۴ - ایساکو با لیست قیمت متغیر')], default='group_1', help_text='گروه محصول برای محاسبه تخفیف', max_length=20, verbose_name='گروه محصول'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='auto_discount_applied',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='تخفیف خودکار اعمال شده'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='cash_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='مبلغ کالاهای نقدی', max_digits=18, verbose_name='مبلغ نقدی پای بار'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='cash_equivalent_of_cheques',
            field=models.DecimalField(decimal_places=0, default=0, help_text='مبلغ نقدی برای پرداخت چک\u200cها', max_digits=18, verbose_name='معادل نقدی چک\u200cها'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='cheque_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='مبلغ کالاهای چکی', max_digits=18, verbose_name='مبلغ چکی'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='cheque_due_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='سررسید میانگین چک'),
        ),
    ]
