# Generated by Django 4.2 on 2025-07-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
