# Generated by Django 5.2.7 on 2025-10-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_invoicesettlementdraft_products_in_updated_adfd58_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='settled_cash_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='مبلغی که از نقدی پای\u200cبار تسویه شده', max_digits=18, verbose_name='مبلغ تسویه شده از نقدی پای\u200cبار'),
        ),
    ]
