# Generated by Django 5.2.4 on 2025-10-25 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_salesinvoice_settled_cash_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="financial_operation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voucher",
                to="products.financialoperation",
                verbose_name="عملیات مالی",
            ),
        ),
    ]
