# Generated by Django 4.2.11 on 2025-07-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_normalized_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100, verbose_name='جمع کل سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'سبد خرید'), ('pending', 'در انتظار تأیید'), ('warehouse', 'ارسال شده به انبار'), ('ready', 'آماده تحویل'), ('delivered', 'تحویل داده شده'), ('parent', 'تفکیک شده به انبارها'), ('completed', 'نهایی شده'), ('backorder', 'در انتظار موجودی'), ('waiting_for_customer_shipment', 'در انتظار ارسال به مشتری'), ('sent_to_warehouse', ' ارسال شده به انبار از بک اوردر'), ('waiting_for_warehouse_confirmation', 'در انتظار تایید انباردار')], default='pending', max_length=100, verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('cart', 'سبد خرید'), ('pending', 'در انتظار تأیید'), ('warehouse', 'ارسال شده به انبار'), ('ready', 'آماده تحویل'), ('delivered', 'تحویل داده شده'), ('parent', 'تفکیک شده به انبارها'), ('completed', 'نهایی شده'), ('backorder', 'در انتظار موجودی'), ('waiting_for_customer_shipment', 'در انتظار ارسال به مشتری'), ('sent_to_warehouse', ' ارسال شده به انبار از بک اوردر'), ('waiting_for_warehouse_confirmation', 'در انتظار تایید انباردار')], max_length=50),
        ),
    ]
