# Generated by Django 4.2 on 2025-07-17 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_order_total_price_alter_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت قدیم')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت جدید')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تغییر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_changes', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تغییر قیمت',
                'verbose_name_plural': 'تغییرات قیمت',
                'ordering': ['-change_date'],
            },
        ),
    ]
