# Generated by Django 4.2.11 on 2025-07-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100, verbose_name='قیمت خرید'),
        ),
    ]
