# Generated by Django 4.2.11 on 2025-07-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد سود'),
        ),
    ]
