# Generated by Django 4.2 on 2025-07-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_profit_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام بانک')),
                ('branch_name', models.CharField(max_length=100, verbose_name='نام شعبه')),
                ('branch_code', models.CharField(max_length=20, verbose_name='کد شعبه')),
                ('account_number', models.CharField(max_length=50, verbose_name='شماره حساب')),
                ('account_type', models.CharField(max_length=50, verbose_name='نوع حساب')),
            ],
            options={
                'verbose_name': 'بانک',
                'verbose_name_plural': 'بانک\u200cها',
            },
        ),
    ]
