# Generated by Django 4.2 on 2025-07-23 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0020_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True, verbose_name='شماره فاکتور')),
                ('invoice_date', models.DateField(verbose_name='تاریخ فاکتور')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='جمع کل فاکتور')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('registered', 'ثبت شده'), ('confirmed', 'تایید شده'), ('cancelled', 'باطل شده')], default='registered', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('settle_cash', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='تسویه نقدی')),
                ('settle_card', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='تسویه کارتخوان')),
                ('settle_bank', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='تسویه بانکی')),
                ('settle_cheque', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='تسویه چک')),
                ('settle_balance', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مانده حساب')),
                ('settle_extra_discount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='تخفیف مازاد')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.customer', verbose_name='طرف حساب')),
            ],
            options={
                'verbose_name': 'فاکتور خرید',
                'verbose_name_plural': 'فاکتورهای خرید',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('price', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='قیمت')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد تخفیف')),
                ('profit_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد سود')),
                ('total', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ کل')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.purchaseinvoice', verbose_name='فاکتور خرید')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'آیتم فاکتور خرید',
                'verbose_name_plural': 'آیتم\u200cهای فاکتور خرید',
            },
        ),
    ]
