# Generated by Django 4.2 on 2025-07-24 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0022_salesinvoice_alter_purchaseinvoice_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'گزارش روزانه'), ('weekly', 'گزارش هفتگی'), ('monthly', 'گزارش ماهانه'), ('yearly', 'گزارش سالانه'), ('custom', 'گزارش دلخواه')], max_length=20, verbose_name='نوع گزارش')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع')),
                ('end_date', django_jalali.db.models.jDateField(verbose_name='تاریخ پایان')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('total_sales', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='مجموع فروش')),
                ('total_sales_count', models.PositiveIntegerField(default=0, verbose_name='تعداد فاکتورهای فروش')),
                ('total_purchases', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='مجموع خرید')),
                ('total_purchases_count', models.PositiveIntegerField(default=0, verbose_name='تعداد فاکتورهای خرید')),
                ('total_cash_settled', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='مجموع تسویه نقدی')),
                ('total_card_settled', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='مجموع تسویه کارت')),
                ('total_bank_settled', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='مجموع تسویه بانکی')),
                ('total_cheque_settled', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='مجموع تسویه چک')),
                ('total_customer_balance', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='مجموع مانده حساب مشتریان')),
                ('total_supplier_balance', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='مجموع مانده حساب تامین\u200cکنندگان')),
                ('total_profit', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='مجموع سود')),
                ('average_profit_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='میانگین درصد سود')),
                ('total_discounts', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='مجموع تخفیفات')),
                ('total_extra_discounts', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='مجموع تخفیفات مازاد')),
                ('total_transactions', models.PositiveIntegerField(default=0, verbose_name='تعداد کل تراکنش\u200cها')),
                ('total_debit', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='مجموع بدهکار')),
                ('total_credit', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='مجموع بستانکار')),
                ('net_balance', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='مانده خالص')),
                ('total_debtors', models.PositiveIntegerField(default=0, verbose_name='تعداد بدهکاران')),
                ('total_creditors', models.PositiveIntegerField(default=0, verbose_name='تعداد بستانکاران')),
                ('total_debtors_amount', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='مجموع مبلغ بدهکاران')),
                ('total_creditors_amount', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='مجموع مبلغ بستانکاران')),
                ('highest_debtor_amount', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='بیشترین مبلغ بدهکار')),
                ('highest_creditor_amount', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='بیشترین مبلغ بستانکار')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'گزارش حسابداری',
                'verbose_name_plural': 'گزارشات حسابداری',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountingReportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('debtor', 'بدهکار'), ('creditor', 'بستانکار')], max_length=10, verbose_name='نوع تراکنش')),
                ('total_sales', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='مجموع فروش')),
                ('total_purchases', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='مجموع خرید')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='تعداد فاکتورهای فروش')),
                ('purchases_count', models.PositiveIntegerField(default=0, verbose_name='تعداد فاکتورهای خرید')),
                ('total_cash_settled', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='تسویه نقدی')),
                ('total_card_settled', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='تسویه کارتی')),
                ('total_bank_settled', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='تسویه بانکی')),
                ('total_cheque_settled', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='تسویه چک')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='مانده حساب')),
                ('last_transaction_date', django_jalali.db.models.jDateField(verbose_name='تاریخ آخرین تراکنش')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.customer', verbose_name='شخص')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='products.accountingreport', verbose_name='گزارش مربوطه')),
            ],
            options={
                'verbose_name': 'جزئیات گزارش حسابداری',
                'verbose_name_plural': 'جزئیات گزارشات حسابداری',
                'ordering': ['-balance', 'customer__last_name'],
            },
        ),
    ]
