# Generated by Django 4.2 on 2025-07-27 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0023_accountingreport_accountingreportdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد حساب')),
                ('name', models.CharField(max_length=200, verbose_name='نام حساب')),
                ('level', models.CharField(choices=[('KOL', 'کل'), ('MOEIN', 'معین'), ('TAFSILI', 'تفصیلی')], max_length=10, verbose_name='سطح حساب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'حساب\u200cها',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50, verbose_name='شماره حساب')),
                ('sheba', models.CharField(max_length=26, unique=True, verbose_name='شماره شبا')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت')),
                ('account_type', models.CharField(choices=[('CHECKING', 'جاری'), ('SAVINGS', 'پس\u200cانداز'), ('CURRENT', 'قرض\u200cالحسنه جاری'), ('SAVING_QARZ', 'قرض\u200cالحسنه پس\u200cانداز')], max_length=20, verbose_name='نوع حساب')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان حساب')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='موجودی اولیه')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='موجودی فعلی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='products.account', verbose_name='حساب مرتبط')),
            ],
            options={
                'verbose_name': 'حساب بانکی',
                'verbose_name_plural': 'حساب\u200cهای بانکی',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='کد ارز')),
                ('name', models.CharField(max_length=50, verbose_name='نام ارز')),
                ('symbol', models.CharField(max_length=5, verbose_name='نماد')),
                ('is_default', models.BooleanField(default=False, verbose_name='ارز پیش\u200cفرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=18, verbose_name='نرخ تبدیل به ارز پیش\u200cفرض')),
            ],
            options={
                'verbose_name': 'ارز',
                'verbose_name_plural': 'ارزها',
            },
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, unique=True, verbose_name='سال مالی')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_closed', models.BooleanField(default=False, verbose_name='بسته شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سال مالی',
                'verbose_name_plural': 'سال\u200cهای مالی',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='شماره سند')),
                ('date', models.DateField(verbose_name='تاریخ سند')),
                ('type', models.CharField(choices=[('TEMPORARY', 'موقت'), ('PERMANENT', 'دائم')], default='TEMPORARY', max_length=20, verbose_name='نوع سند')),
                ('description', models.TextField(verbose_name='شرح سند')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='تأیید کننده')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.financialyear', verbose_name='سال مالی')),
            ],
            options={
                'verbose_name': 'سند حسابداری',
                'verbose_name_plural': 'اسناد حسابداری',
                'unique_together': {('financial_year', 'number')},
            },
        ),
        migrations.RemoveField(
            model_name='bank',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='branch_code',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='branch_name',
        ),
        migrations.AddField(
            model_name='bank',
            name='code',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='کد بانک'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.CreateModel(
            name='VoucherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='شرح')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='بدهکار')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='بستانکار')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه مرجع')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='نوع مرجع')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.account', verbose_name='حساب')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.voucher', verbose_name='سند')),
            ],
            options={
                'verbose_name': 'آرتیکل سند',
                'verbose_name_plural': 'آرتیکل\u200cهای سند',
            },
        ),
        migrations.CreateModel(
            name='CheckBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=50, unique=True, verbose_name='سریال دسته چک')),
                ('start_number', models.IntegerField(verbose_name='شماره شروع')),
                ('end_number', models.IntegerField(verbose_name='شماره پایان')),
                ('current_number', models.IntegerField(verbose_name='شماره فعلی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.bankaccount', verbose_name='حساب بانکی')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'دسته چک',
                'verbose_name_plural': 'دسته چک\u200cها',
            },
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان صندوق')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='موجودی اولیه')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='موجودی فعلی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='products.account', verbose_name='حساب مرتبط')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'صندوق',
                'verbose_name_plural': 'صندوق\u200cها',
            },
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.bank', verbose_name='بانک'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد گروه')),
                ('name', models.CharField(max_length=100, verbose_name='نام گروه')),
                ('type', models.CharField(choices=[('ASSET', 'دارایی'), ('LIABILITY', 'بدهی'), ('EQUITY', 'سرمایه'), ('REVENUE', 'درآمد'), ('EXPENSE', 'هزینه')], max_length=20, verbose_name='نوع حساب')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.accountgroup', verbose_name='گروه والد')),
            ],
            options={
                'verbose_name': 'گروه حساب',
                'verbose_name_plural': 'گروه\u200cهای حساب',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.currency', verbose_name='ارز'),
        ),
        migrations.AddField(
            model_name='account',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.accountgroup', verbose_name='گروه حساب'),
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.account', verbose_name='حساب والد'),
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='شماره چک')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='مبلغ')),
                ('date', models.DateField(verbose_name='تاریخ سررسید')),
                ('status', models.CharField(choices=[('UNUSED', 'استفاده نشده'), ('ISSUED', 'صادر شده'), ('RECEIVED', 'دریافت شده'), ('DEPOSITED', 'واگذار شده'), ('CLEARED', 'وصول شده'), ('BOUNCED', 'برگشت خورده'), ('VOID', 'باطل شده')], default='UNUSED', max_length=20, verbose_name='وضعیت')),
                ('payee', models.CharField(max_length=200, verbose_name='در وجه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='نام بانک')),
                ('bank_branch', models.CharField(blank=True, max_length=100, verbose_name='شعبه بانک')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='شماره حساب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('checkbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.checkbook', verbose_name='دسته چک')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'چک',
                'verbose_name_plural': 'چک\u200cها',
                'unique_together': {('checkbook', 'number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('bank', 'account_number')},
        ),
    ]
