# Generated by Django 5.2.4 on 2025-08-03 16:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_account_bankaccount_currency_financialyear_voucher_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['code'], 'verbose_name': 'حساب', 'verbose_name_plural': 'حساب\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='accountgroup',
            options={'ordering': ['code'], 'verbose_name': 'گروه حساب', 'verbose_name_plural': 'گروه\u200cهای حساب'},
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['name'], 'verbose_name': 'بانک', 'verbose_name_plural': 'بانک\u200cها'},
        ),
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='موجودی فعلی'),
        ),
        migrations.AddField(
            model_name='account',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='موجودی اولیه'),
        ),
        migrations.AddField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AddField(
            model_name='accountgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountgroup',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='accountgroup',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='accountgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AddField(
            model_name='bank',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='bank',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن'),
        ),
        migrations.AddField(
            model_name='bank',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='وب\u200cسایت'),
        ),
        migrations.AlterField(
            model_name='accountgroup',
            name='code',
            field=models.CharField(choices=[('1000', 'دارایی\u200cهای جاری'), ('1100', 'موجودی نقد'), ('1200', 'سرمایه\u200cگذاری\u200cهای کوتاه\u200cمدت'), ('1300', 'حساب\u200cها و اسناد دریافتنی'), ('1400', 'موجودی کالا'), ('1500', 'پیش\u200cپرداخت\u200cها'), ('1600', 'دارایی\u200cهای ثابت'), ('1700', 'سرمایه\u200cگذاری\u200cهای بلندمدت'), ('1800', 'دارایی\u200cهای نامشهود'), ('2000', 'بدهی\u200cهای جاری'), ('2100', 'حساب\u200cها و اسناد پرداختنی'), ('2200', 'پیش\u200cدریافت\u200cها'), ('2300', 'ذخایر'), ('2400', 'بدهی\u200cهای بلندمدت'), ('3000', 'سرمایه'), ('3100', 'سرمایه\u200cگذاری\u200cهای صاحبان سهام'), ('3200', 'سود انباشته'), ('3300', 'سود سال جاری'), ('4000', 'درآمدهای عملیاتی'), ('4100', 'فروش کالا'), ('4200', 'فروش خدمات'), ('4300', 'درآمدهای غیرعملیاتی'), ('4400', 'سود سرمایه\u200cگذاری\u200cها'), ('5000', 'هزینه\u200cهای عملیاتی'), ('5100', 'بهای تمام شده کالای فروش رفته'), ('5200', 'هزینه\u200cهای فروش'), ('5300', 'هزینه\u200cهای اداری'), ('5400', 'هزینه\u200cهای مالی'), ('5500', 'هزینه\u200cهای غیرعملیاتی')], max_length=10, unique=True, verbose_name='کد گروه'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='code',
            field=models.CharField(choices=[('001', 'بانک مرکزی جمهوری اسلامی ایران'), ('010', 'بانک ملی ایران'), ('011', 'بانک سپه'), ('012', 'بانک صادرات ایران'), ('013', 'بانک کشاورزی'), ('014', 'بانک مسکن'), ('015', 'بانک صنعت و معدن'), ('016', 'بانک توسعه صادرات ایران'), ('017', 'بانک توسعه تعاون'), ('018', 'بانک تجارت'), ('019', 'بانک ملت'), ('020', 'بانک رفاه کارگران'), ('021', 'بانک پست بانک ایران'), ('022', 'بانک پارسیان'), ('023', 'بانک اقتصاد نوین'), ('024', 'بانک سینا'), ('025', 'بانک سرمایه'), ('026', 'بانک سامان'), ('027', 'بانک پاسارگاد'), ('028', 'بانک کارآفرین'), ('029', 'بانک شهر'), ('030', 'بانک دی'), ('031', 'بانک انصار'), ('032', 'بانک مهر ایران'), ('033', 'بانک آینده'), ('034', 'بانک گردشگری'), ('035', 'بانک ایران زمین'), ('036', 'بانک قوامین'), ('037', 'بانک خاورمیانه'), ('038', 'بانک کوثر'), ('039', 'بانک مهر اقتصاد'), ('040', 'بانک حکمت ایرانیان'), ('041', 'بانک کارگزاران'), ('042', 'بانک رسالت'), ('043', 'بانک قرض\u200cالحسنه مهر ایران'), ('044', 'بانک قرض\u200cالحسنه رسالت'), ('045', 'بانک قرض\u200cالحسنه قوامین'), ('046', 'بانک قرض\u200cالحسنه مهر'), ('047', 'بانک قرض\u200cالحسنه امام رضا'), ('048', 'بانک قرض\u200cالحسنه نور'), ('049', 'بانک قرض\u200cالحسنه ولیعصر'), ('050', 'بانک قرض\u200cالحسنه عسکریه'), ('051', 'بانک قرض\u200cالحسنه انصار'), ('052', 'بانک قرض\u200cالحسنه رسالت'), ('053', 'بانک قرض\u200cالحسنه مهر'), ('054', 'بانک قرض\u200cالحسنه قوامین'), ('055', 'بانک قرض\u200cالحسنه امام رضا'), ('056', 'بانک قرض\u200cالحسنه نور'), ('057', 'بانک قرض\u200cالحسنه ولیعصر'), ('058', 'بانک قرض\u200cالحسنه عسکریه'), ('059', 'بانک قرض\u200cالحسنه انصار'), ('060', 'بانک قرض\u200cالحسنه رسالت'), ('061', 'بانک قرض\u200cالحسنه مهر'), ('062', 'بانک قرض\u200cالحسنه قوامین'), ('063', 'بانک قرض\u200cالحسنه امام رضا'), ('064', 'بانک قرض\u200cالحسنه نور'), ('065', 'بانک قرض\u200cالحسنه ولیعصر'), ('066', 'بانک قرض\u200cالحسنه عسکریه'), ('067', 'بانک قرض\u200cالحسنه انصار'), ('068', 'بانک قرض\u200cالحسنه رسالت'), ('069', 'بانک قرض\u200cالحسنه مهر'), ('070', 'بانک قرض\u200cالحسنه قوامین'), ('071', 'بانک قرض\u200cالحسنه امام رضا'), ('072', 'بانک قرض\u200cالحسنه نور'), ('073', 'بانک قرض\u200cالحسنه ولیعصر'), ('074', 'بانک قرض\u200cالحسنه عسکریه'), ('075', 'بانک قرض\u200cالحسنه انصار'), ('076', 'بانک قرض\u200cالحسنه رسالت'), ('077', 'بانک قرض\u200cالحسنه مهر'), ('078', 'بانک قرض\u200cالحسنه قوامین'), ('079', 'بانک قرض\u200cالحسنه امام رضا'), ('080', 'بانک قرض\u200cالحسنه نور'), ('081', 'بانک قرض\u200cالحسنه ولیعصر'), ('082', 'بانک قرض\u200cالحسنه عسکریه'), ('083', 'بانک قرض\u200cالحسنه انصار'), ('084', 'بانک قرض\u200cالحسنه رسالت'), ('085', 'بانک قرض\u200cالحسنه مهر'), ('086', 'بانک قرض\u200cالحسنه قوامین'), ('087', 'بانک قرض\u200cالحسنه امام رضا'), ('088', 'بانک قرض\u200cالحسنه نور'), ('089', 'بانک قرض\u200cالحسنه ولیعصر'), ('090', 'بانک قرض\u200cالحسنه عسکریه'), ('091', 'بانک قرض\u200cالحسنه انصار'), ('092', 'بانک قرض\u200cالحسنه رسالت'), ('093', 'بانک قرض\u200cالحسنه مهر'), ('094', 'بانک قرض\u200cالحسنه قوامین'), ('095', 'بانک قرض\u200cالحسنه امام رضا'), ('096', 'بانک قرض\u200cالحسنه نور'), ('097', 'بانک قرض\u200cالحسنه ولیعصر'), ('098', 'بانک قرض\u200cالحسنه عسکریه'), ('099', 'بانک قرض\u200cالحسنه انصار')], max_length=20, unique=True, verbose_name='کد بانک'),
        ),
        migrations.CreateModel(
            name='CustomerBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='موجودی فعلی')),
                ('total_received', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='مجموع دریافتی')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='مجموع پرداختی')),
                ('last_transaction_date', models.DateField(blank=True, null=True, verbose_name='تاریخ آخرین تراکنش')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'موجودی مشتری',
                'verbose_name_plural': 'موجودی مشتریان',
            },
        ),
        migrations.CreateModel(
            name='DocumentArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_type', models.CharField(choices=[('DEBIT', 'بدهکار'), ('CREDIT', 'بستانکار')], max_length=10, verbose_name='نوع آرتیکل')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='مبلغ')),
                ('description', models.CharField(max_length=500, verbose_name='شرح')),
                ('category', models.CharField(choices=[('CASH', 'نقدی'), ('BANK', 'بانکی'), ('CUSTOMER', 'مشتری'), ('SUPPLIER', 'تأمین\u200cکننده'), ('SALES', 'فروش'), ('PURCHASE', 'خرید'), ('EXPENSE', 'هزینه'), ('INCOME', 'درآمد'), ('ASSET', 'دارایی'), ('LIABILITY', 'بدهی'), ('EQUITY', 'سرمایه'), ('OTHER', 'سایر')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه مرجع')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='نوع مرجع')),
                ('is_posted', models.BooleanField(default=False, verbose_name='ثبت شده')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ثبت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.account', verbose_name='حساب')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_articles', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='products.voucher', verbose_name='سند')),
            ],
            options={
                'verbose_name': 'آرتیکل سند',
                'verbose_name_plural': 'آرتیکل\u200cهای سند',
                'ordering': ['voucher', 'article_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinancialOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('RECEIVE_FROM_CUSTOMER', 'دریافت از مشتری'), ('PAY_TO_CUSTOMER', 'پرداخت به مشتری'), ('RECEIVE_FROM_BANK', 'دریافت از بانک'), ('PAY_TO_BANK', 'پرداخت به بانک'), ('BANK_TRANSFER', 'حواله بانکی'), ('CASH_WITHDRAWAL', 'برداشت نقدی از بانک'), ('PAYMENT_TO_CASH', 'پرداخت به صندوق'), ('PAYMENT_FROM_CASH', 'پرداخت از صندوق'), ('CAPITAL_INVESTMENT', 'سرمایه گذاری'), ('PETTY_CASH', 'تنخواه')], max_length=50, verbose_name='نوع عملیات')),
                ('operation_number', models.CharField(max_length=50, unique=True, verbose_name='شماره عملیات')),
                ('date', models.DateField(verbose_name='تاریخ عملیات')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='مبلغ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('CONFIRMED', 'تأیید شده'), ('CANCELLED', 'باطل شده')], default='DRAFT', max_length=20, verbose_name='وضعیت')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='نام بانک')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='شماره حساب')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدی'), ('bank_transfer', 'حواله بانکی'), ('cheque', 'چک')], max_length=20, verbose_name='روش پرداخت')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='شماره مرجع')),
                ('cheque_number', models.CharField(blank=True, max_length=50, verbose_name='شماره چک')),
                ('cheque_date', models.DateField(blank=True, null=True, verbose_name='تاریخ چک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_operations', to=settings.AUTH_USER_MODEL, verbose_name='تأیید کننده')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'عملیات مالی',
                'verbose_name_plural': 'عملیات مالی',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام صندوق')),
                ('fund_type', models.CharField(choices=[('CASH', 'صندوق نقدی'), ('BANK', 'حساب بانکی'), ('PETTY_CASH', 'تنخواه')], max_length=20, verbose_name='نوع صندوق')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='موجودی اولیه')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='موجودی فعلی')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='نام بانک')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='شماره حساب')),
                ('sheba_number', models.CharField(blank=True, max_length=26, verbose_name='شماره شبا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'صندوق',
                'verbose_name_plural': 'صندوق\u200cها',
                'ordering': ['fund_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEBIT', 'بدهکار'), ('CREDIT', 'بستانکار')], max_length=10, verbose_name='نوع تراکنش')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='مبلغ')),
                ('description', models.CharField(max_length=255, verbose_name='شرح')),
                ('date', models.DateField(verbose_name='تاریخ تراکنش')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='products.financialoperation', verbose_name='عملیات')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.fund', verbose_name='صندوق')),
            ],
            options={
                'verbose_name': 'تراکنش مالی',
                'verbose_name_plural': 'تراکنش\u200cهای مالی',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FundBalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('previous_balance', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='موجودی قبلی')),
                ('change_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='مبلغ تغییر')),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='موجودی جدید')),
                ('description', models.CharField(max_length=255, verbose_name='شرح')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_history', to='products.fund', verbose_name='صندوق')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.financialoperation', verbose_name='عملیات مرتبط')),
            ],
            options={
                'verbose_name': 'تاریخچه موجودی صندوق',
                'verbose_name_plural': 'تاریخچه موجودی صندوق\u200cها',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PettyCashOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_number', models.CharField(max_length=50, unique=True, verbose_name='شماره عملیات')),
                ('operation_type', models.CharField(choices=[('ADD', 'افزودن به تنخواه'), ('WITHDRAW', 'برداشت از تنخواه')], max_length=20, verbose_name='نوع عملیات')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='مبلغ')),
                ('reason', models.CharField(max_length=100, verbose_name='دلیل عملیات')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'عملیات تنخواه',
                'verbose_name_plural': 'عملیات تنخواه',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='مبلغ')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدی'), ('bank_transfer', 'حواله بانکی'), ('cheque', 'چک')], max_length=20, verbose_name='روش پرداخت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'رسید دریافت',
                'verbose_name_plural': 'رسیدهای دریافت',
                'ordering': ['-date'],
            },
        ),
    ]
