# Generated by Django 4.2.11 on 2025-08-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_cashregister_options_alter_bank_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='check',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'چک', 'verbose_name_plural': 'چک\u200cها'},
        ),
    ]
