# Generated by Django 4.2.11 on 2025-08-05 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_check_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashoperation',
            name='source_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_source_operations', to='products.bankaccount', verbose_name='حساب بانکی منبع'),
        ),
        migrations.AddField(
            model_name='pettycashoperation',
            name='source_fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_source_operations', to='products.fund', verbose_name='صندوق منبع'),
        ),
        migrations.AlterField(
            model_name='pettycashoperation',
            name='reason',
            field=models.CharField(choices=[('expense', 'هزینه روزانه'), ('emergency', 'اورژانس'), ('maintenance', 'نگهداری'), ('stationery', 'خرید لوازم التحریر'), ('transportation', 'هزینه حمل و نقل'), ('meals', 'هزینه غذا'), ('other', 'سایر')], max_length=100, verbose_name='دلیل عملیات'),
        ),
    ]
