# Generated by Django 4.2.11 on 2025-08-05 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_pettycashoperation_source_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='fund_type',
            field=models.CharField(choices=[('CASH', 'صندوق نقدی'), ('BANK', 'حساب بانکی')], max_length=20, verbose_name='نوع صندوق'),
        ),
        migrations.CreateModel(
            name='FundStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('operation_type', models.CharField(max_length=50, verbose_name='نوع عملیات')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='مبلغ')),
                ('running_balance', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='مانده پس از عملیات')),
                ('description', models.CharField(max_length=255, verbose_name='شرح')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه مرجع')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='نوع مرجع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='products.fund', verbose_name='صندوق')),
            ],
            options={
                'verbose_name': 'صورتحساب صندوق',
                'verbose_name_plural': 'صورتحساب\u200cهای صندوق',
                'ordering': ['fund', 'date', 'created_at'],
            },
        ),
    ]
