# Generated by Django 4.2.11 on 2025-08-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_fund_fund_type_fundstatement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentArticle',
        ),
    ]
