# Generated by Django 4.2.11 on 2025-08-05 12:48

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_delete_documentarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ سررسید'),
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='last_transaction_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ آخرین تراکنش'),
        ),
        migrations.AlterField(
            model_name='financialoperation',
            name='cheque_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ چک'),
        ),
        migrations.AlterField(
            model_name='financialoperation',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ عملیات'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ تراکنش'),
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='end_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='start_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='fundbalancehistory',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='fundstatement',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='pettycashoperation',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ سند'),
        ),
    ]
