# Generated by Django 4.2.11 on 2025-08-05 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0031_alter_check_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='has_card_reader',
            field=models.BooleanField(default=False, verbose_name='دارای کارت\u200cخوان'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='terminal_number',
            field=models.CharField(blank=True, help_text='در صورت فعال بودن کارت\u200cخوان، شماره پایانه را وارد کنید', max_length=50, null=True, verbose_name='شماره پایانه'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='card_number',
            field=models.CharField(blank=True, help_text='شماره کارت باید دقیقاً 16 رقم باشد', max_length=16, null=True, verbose_name='شماره کارت'),
        ),
        migrations.CreateModel(
            name='CardReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_number', models.CharField(max_length=50, unique=True, verbose_name='شماره پایانه')),
                ('terminal_name', models.CharField(max_length=100, verbose_name='نام پایانه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_readers', to='products.bankaccount', verbose_name='حساب بانکی')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'کارت\u200cخوان',
                'verbose_name_plural': 'کارت\u200cخوان\u200cها',
                'ordering': ['bank_account', 'terminal_number'],
            },
        ),
    ]
