# Generated by Django 4.2.11 on 2025-08-05 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0032_bankaccount_has_card_reader_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardreader',
            options={'ordering': ['bank_account', 'device'], 'verbose_name': 'کارت\u200cخوان', 'verbose_name_plural': 'کارت\u200cخوان\u200cها'},
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='has_card_reader',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='terminal_number',
        ),
        migrations.CreateModel(
            name='CardReaderDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دستگاه')),
                ('device_type', models.CharField(choices=[('POS', 'دستگاه POS'), ('PINPAD', 'دستگاه PINPAD'), ('MOBILE', 'دستگاه موبایل'), ('TABLET', 'دستگاه تبلت'), ('OTHER', 'سایر')], max_length=20, verbose_name='نوع دستگاه')),
                ('terminal_number', models.CharField(max_length=50, unique=True, verbose_name='شماره پایانه')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره سریال')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='سازنده')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='مدل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'دستگاه کارت\u200cخوان',
                'verbose_name_plural': 'دستگاه\u200cهای کارت\u200cخوان',
                'ordering': ['name', 'terminal_number'],
            },
        ),
        migrations.AddField(
            model_name='cardreader',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.cardreaderdevice', verbose_name='دستگاه کارت\u200cخوان'),
        ),
        migrations.AlterUniqueTogether(
            name='cardreader',
            unique_together={('bank_account', 'device')},
        ),
        migrations.RemoveField(
            model_name='cardreader',
            name='terminal_name',
        ),
        migrations.RemoveField(
            model_name='cardreader',
            name='terminal_number',
        ),
    ]
