# Generated by Django 4.2.11 on 2025-08-05 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_alter_cardreader_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='card_reader_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.cardreaderdevice', verbose_name='دستگاه کارت\u200cخوان'),
        ),
        migrations.AddField(
            model_name='cardreaderdevice',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.bank', verbose_name='بانک مرتبط'),
        ),
        migrations.AddField(
            model_name='cardreaderdevice',
            name='support_company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شرکت پشتیبان'),
        ),
        migrations.AddField(
            model_name='cardreaderdevice',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل پشتیبان'),
        ),
        migrations.AddField(
            model_name='cardreaderdevice',
            name='support_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس پشتیبان'),
        ),
        migrations.DeleteModel(
            name='CardReader',
        ),
    ]
