# Generated by Django 4.2.11 on 2025-08-05 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_bankaccount_card_reader_device_cardreaderdevice_bank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardreaderdevice',
            name='bank',
        ),
        migrations.AddField(
            model_name='cardreaderdevice',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.bankaccount', verbose_name='حساب بانکی مرتبط'),
        ),
    ]
