# Generated by Django 4.2.11 on 2025-08-05 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_remove_cardreaderdevice_bank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='card_reader_device',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='card_reader_device_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts_1', to='products.cardreaderdevice', verbose_name='دستگاه کارت\u200cخوان 1'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='card_reader_device_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts_2', to='products.cardreaderdevice', verbose_name='دستگاه کارت\u200cخوان 2'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='card_reader_device_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts_3', to='products.cardreaderdevice', verbose_name='دستگاه کارت\u200cخوان 3'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='card_reader_device_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts_4', to='products.cardreaderdevice', verbose_name='دستگاه کارت\u200cخوان 4'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='has_card_reader',
            field=models.BooleanField(default=False, verbose_name='دارای کارت\u200cخوان'),
        ),
    ]
