# Generated by Django 4.2.11 on 2025-08-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_remove_bankaccount_card_reader_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='card_number',
            field=models.CharField(blank=True, help_text='شماره کارت باید دقیقاً 16 رقم باشد', max_length=25, null=True, verbose_name='شماره کارت'),
        ),
    ]
