# Generated by Django 4.2.11 on 2025-08-05 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0037_alter_bankaccount_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'ورودی'), ('OUT', 'خروجی')], max_length=10, verbose_name='نوع تراکنش')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='مبلغ')),
                ('description', models.CharField(max_length=255, verbose_name='شرح')),
                ('date', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه مرجع')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='نوع مرجع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='products.fund', verbose_name='صندوق')),
            ],
            options={
                'verbose_name': 'گردش صندوق',
                'verbose_name_plural': 'گردش صندوق\u200cها',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
