# Generated by Django 4.2.11 on 2025-08-05 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_fundtransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FundTransaction',
        ),
    ]
