# Generated by Django 4.2.11 on 2025-08-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_fundtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='fund_type',
            field=models.CharField(choices=[('CASH', 'صندوق نقدی'), ('BANK', 'حساب بانکی'), ('PETTY_CASH', 'تنخواه')], max_length=20, verbose_name='نوع صندوق'),
        ),
    ]
