# Generated by Django 4.2.11 on 2025-08-05 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_alter_fund_fund_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialoperation',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.fund', verbose_name='صندوق مرتبط'),
        ),
    ]
