# Generated by Django 5.2.4 on 2025-08-09 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_add_created_by_to_fundstatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialoperation',
            name='card_reader_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.cardreaderdevice', verbose_name='دستگاه کارت\u200cخوان'),
        ),
        migrations.AlterField(
            model_name='financialoperation',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدی'), ('bank_transfer', 'حواله بانکی'), ('cheque', 'چک'), ('pos', 'دستگاه POS')], max_length=20, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدی'), ('bank_transfer', 'حواله بانکی'), ('cheque', 'چک'), ('pos', 'دستگاه POS')], max_length=20, verbose_name='روش پرداخت'),
        ),
    ]
