# Generated by Django 5.2.4 on 2025-08-11 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_financialoperation_card_reader_device_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='check',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='check',
            name='endorsement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='پشت نمره'),
        ),
        migrations.AddField(
            model_name='check',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام صاحب حساب'),
        ),
        migrations.AddField(
            model_name='check',
            name='owner_national_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کدملی صاحب حساب'),
        ),
        migrations.AddField(
            model_name='check',
            name='sayadi_id',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='شناسه صیادی'),
        ),
        migrations.AddField(
            model_name='check',
            name='series',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='سری چک'),
        ),
        migrations.AlterField(
            model_name='check',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='check',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شعبه بانک'),
        ),
        migrations.AlterField(
            model_name='check',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام بانک'),
        ),
        migrations.AlterField(
            model_name='check',
            name='checkbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.checkbook', verbose_name='دسته چک (برای چک\u200cهای پرداختی)'),
        ),
        migrations.AlterField(
            model_name='check',
            name='number',
            field=models.CharField(max_length=50, verbose_name='شماره/سریال چک'),
        ),
        migrations.AddConstraint(
            model_name='check',
            constraint=models.UniqueConstraint(condition=models.Q(('checkbook__isnull', False)), fields=('checkbook', 'number'), name='unique_issued_check'),
        ),
    ]
