# Generated by Django 5.2.4 on 2025-08-11 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_alter_check_unique_together_check_endorsement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedCheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endorsement', models.CharField(blank=True, max_length=255, null=True, verbose_name='پشت نمره')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('bank_name', models.CharField(max_length=100, verbose_name='نام بانک')),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شعبه')),
                ('series', models.CharField(blank=True, max_length=50, null=True, verbose_name='سری چک')),
                ('serial', models.CharField(blank=True, max_length=50, null=True, verbose_name='سریال چک')),
                ('sayadi_id', models.CharField(max_length=16, unique=True, verbose_name='شناسه صیادی')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ')),
                ('owner_name', models.CharField(max_length=255, verbose_name='صاحب حساب')),
                ('national_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='کدملی صاحب حساب')),
                ('account_number', models.CharField(max_length=50, verbose_name='شماره حساب')),
                ('status', models.CharField(choices=[('RECEIVED', 'دریافت شده'), ('DEPOSITED', 'واگذار به بانک'), ('CLEARED', 'وصول شده'), ('BOUNCED', 'برگشت خورده'), ('RETURNED', 'مسترد شده')], default='RECEIVED', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_received_cheques', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_cheques', to='products.customer', verbose_name='مشتری')),
                ('financial_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_cheques', to='products.financialoperation', verbose_name='عملیات مالی')),
            ],
            options={
                'verbose_name': 'چک دریافتی',
                'verbose_name_plural': 'چک\u200cهای دریافتی',
                'ordering': ['-due_date'],
            },
        ),
    ]
