# Generated by Django 5.2.4 on 2025-08-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_receivedcheque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedcheque',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'دریافت شده'), ('DEPOSITED', 'واگذار به بانک'), ('CLEARED', 'وصول شده'), ('MANUALLY_CLEARED', 'وصول به صورت دستی'), ('SPENT', 'خرج شده'), ('BOUNCED', 'برگشت خورده'), ('RETURNED', 'مسترد شده')], default='RECEIVED', max_length=20, verbose_name='وضعیت'),
        ),
    ]
