# Generated by Django 5.2.4 on 2025-08-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_alter_receivedcheque_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedcheque',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام دریافت\u200cکننده (در صورت خرج چک)'),
        ),
    ]
