# Generated by Django 4.2.11 on 2025-08-13 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0049_receivedcheque_recipient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedcheque',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AddField(
            model_name='receivedcheque',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_received_cheques', to=settings.AUTH_USER_MODEL, verbose_name='حذف کننده'),
        ),
        migrations.AddField(
            model_name='receivedcheque',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف شده'),
        ),
    ]
