# Generated by Django 4.2.11 on 2025-08-13 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0050_add_soft_delete_to_received_cheque'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialoperation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ باطل'),
        ),
        migrations.AddField(
            model_name='financialoperation',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_operations', to=settings.AUTH_USER_MODEL, verbose_name='باطل کننده'),
        ),
    ]
