# Generated by Django 4.2.11 on 2025-08-13 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0051_add_cancellation_fields_to_financial_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationFieldChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50, verbose_name='نام فیلد')),
                ('field_label', models.CharField(max_length=100, verbose_name='برچسب فیلد')),
                ('old_value', models.TextField(blank=True, verbose_name='مقدار قبلی')),
                ('new_value', models.TextField(blank=True, verbose_name='مقدار جدید')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تغییر')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تغییر دهنده')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_changes', to='products.financialoperation', verbose_name='عملیات مالی')),
            ],
            options={
                'verbose_name': 'تغییر فیلد عملیات',
                'verbose_name_plural': 'تغییرات فیلدهای عملیات',
                'ordering': ['-changed_at'],
            },
        ),
    ]
