# Generated by Django 5.2.4 on 2025-08-15 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_add_operation_field_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialoperation',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='financialoperation',
            name='cancelled_by',
        ),
        migrations.AddField(
            model_name='receivedcheque',
            name='spending_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spent_cheques', to='products.financialoperation', verbose_name='عملیات خرج چک'),
        ),
        migrations.AlterField(
            model_name='receivedcheque',
            name='financial_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_cheques', to='products.financialoperation', verbose_name='عملیات مالی دریافت'),
        ),
        migrations.DeleteModel(
            name='OperationFieldChange',
        ),
    ]
