# Generated by Django 5.2.4 on 2025-08-15 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_remove_financialoperation_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='issuing_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_checks', to='products.financialoperation', verbose_name='عملیات صدور چک'),
        ),
    ]
