# Generated by Django 5.2.4 on 2025-08-15 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_check_issuing_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='issuing_operation',
        ),
        migrations.RemoveField(
            model_name='receivedcheque',
            name='spending_operation',
        ),
        migrations.AddField(
            model_name='financialoperation',
            name='spent_cheques',
            field=models.ManyToManyField(blank=True, related_name='spending_operations', to='products.receivedcheque', verbose_name='چک\u200cهای خرج شده'),
        ),
        migrations.AlterField(
            model_name='financialoperation',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدی'), ('bank_transfer', 'حواله بانکی'), ('cheque', 'چک'), ('spend_cheque', 'خرج چک'), ('pos', 'دستگاه POS')], max_length=20, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدی'), ('bank_transfer', 'حواله بانکی'), ('cheque', 'چک'), ('spend_cheque', 'خرج چک'), ('pos', 'دستگاه POS')], max_length=20, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='receivedcheque',
            name='financial_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_cheques', to='products.financialoperation', verbose_name='عملیات مالی'),
        ),
    ]
