# Generated by Django 5.2.4 on 2025-08-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_remove_check_issuing_operation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدی'), ('bank_transfer', 'حواله بانکی'), ('cheque', 'چک'), ('pos', 'دستگاه POS')], max_length=20, verbose_name='روش پرداخت'),
        ),
    ]
