# Generated by Django 5.2.4 on 2025-08-18 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0056_alter_receipt_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='financial_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_checks', to='products.financialoperation', verbose_name='عملیات مالی صدور'),
        ),
    ]
