# Generated by Django 5.2.4 on 2025-08-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0057_check_financial_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialoperation',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدی'), ('bank_transfer', 'حواله بانکی'), ('cheque', 'چک'), ('spend_cheque', 'خرج چک'), ('mixed_cheque', 'ترکیب چک\u200cها'), ('pos', 'دستگاه POS')], max_length=20, verbose_name='روش پرداخت'),
        ),
    ]
