# Generated by Django 4.2.11 on 2025-08-18 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0059_add_deposit_to_bank_operation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedcheque',
            name='deposited_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposited_checks', to='products.bankaccount', verbose_name='حساب بانکی واگذار شده'),
        ),
    ]
