# Generated by Django 4.2.11 on 2025-08-19 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0060_add_deposited_bank_account_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receivedcheque',
            options={'ordering': ['-cleared_at', '-due_date', '-created_at'], 'verbose_name': 'چک دریافتی', 'verbose_name_plural': 'چک\u200cهای دریافتی'},
        ),
        migrations.AddField(
            model_name='receivedcheque',
            name='bounced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ برگشت'),
        ),
        migrations.AddField(
            model_name='receivedcheque',
            name='bounced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounced_received_cheques', to=settings.AUTH_USER_MODEL, verbose_name='برگشت دهنده'),
        ),
        migrations.AddField(
            model_name='receivedcheque',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ وصول'),
        ),
        migrations.AddField(
            model_name='receivedcheque',
            name='cleared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_received_cheques', to=settings.AUTH_USER_MODEL, verbose_name='وصول کننده'),
        ),
    ]
