# Generated by Django 4.2.11 on 2025-08-19 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0061_add_check_clearance_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='check',
            options={'ordering': ['-cleared_at', '-bounced_at', '-date', '-created_at'], 'verbose_name': 'چک', 'verbose_name_plural': 'چک\u200cها'},
        ),
        migrations.AddField(
            model_name='check',
            name='bounced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ برگشت'),
        ),
        migrations.AddField(
            model_name='check',
            name='bounced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounced_issued_checks', to=settings.AUTH_USER_MODEL, verbose_name='برگشت دهنده'),
        ),
        migrations.AddField(
            model_name='check',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ وصول'),
        ),
        migrations.AddField(
            model_name='check',
            name='cleared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_issued_checks', to=settings.AUTH_USER_MODEL, verbose_name='وصول کننده'),
        ),
    ]
