# Generated by Django 4.2.11 on 2025-08-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0062_add_issued_check_clearance_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='check',
            options={'ordering': ['-date', '-cleared_at', '-bounced_at', '-created_at'], 'verbose_name': 'چک', 'verbose_name_plural': 'چک\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='receivedcheque',
            options={'ordering': ['-due_date', '-cleared_at', '-created_at'], 'verbose_name': 'چک دریافتی', 'verbose_name_plural': 'چک\u200cهای دریافتی'},
        ),
    ]
