# Generated by Django 4.2.11 on 2025-08-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0063_update_ordering_by_due_date'),
    ]

    operations = [
    ]
