# Generated by Django 4.2.11 on 2025-08-19 12:29

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0064_add_check_effective_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ سررسید'),
        ),
    ]
