# Generated by Django 4.2.11 on 2025-08-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0065_alter_check_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='check',
            name='payee',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='در وجه'),
        ),
    ]
