# Generated by Django 4.2.11 on 2025-08-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0066_alter_check_description_alter_check_payee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialoperation',
            name='operation_type',
            field=models.CharField(choices=[('RECEIVE_FROM_CUSTOMER', 'دریافت از مشتری'), ('PAY_TO_CUSTOMER', 'پرداخت به مشتری'), ('RECEIVE_FROM_BANK', 'دریافت از بانک'), ('PAY_TO_BANK', 'پرداخت به بانک'), ('BANK_TRANSFER', 'حواله بانکی'), ('CASH_WITHDRAWAL', 'برداشت نقدی از بانک'), ('PAYMENT_TO_CASH', 'پرداخت به صندوق'), ('PAYMENT_FROM_CASH', 'پرداخت از صندوق'), ('CAPITAL_INVESTMENT', 'سرمایه گذاری'), ('PETTY_CASH', 'تنخواه'), ('DEPOSIT_TO_BANK', 'واگذاری چک به بانک'), ('CHECK_RESET_FROM_CLEARED', 'بازگشت چک وصول شده به حالت اولیه'), ('CHECK_RESET_FROM_BOUNCED', 'بازگشت چک برگشت خورده به حالت اولیه'), ('CHECK_RESET_FROM_ISSUED', 'بازگشت چک صادر شده به حالت اولیه')], max_length=50, verbose_name='نوع عملیات'),
        ),
    ]
