# Generated by Django 4.2.11 on 2025-08-19 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0067_alter_financialoperation_operation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialoperation',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.bankaccount', verbose_name='حساب بانکی'),
        ),
    ]
