# Generated by Django 4.2.11 on 2025-08-19 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0068_financialoperation_bank_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialoperation',
            options={'verbose_name': 'عملیات مالی', 'verbose_name_plural': 'عملیات مالی'},
        ),
    ]
