# Generated by Django 4.2.11 on 2025-08-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0069_alter_financialoperation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialoperation',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدی'), ('bank_transfer', 'حواله بانکی'), ('cheque', 'چک'), ('spend_cheque', 'خرج چک'), ('mixed_cheque', 'ترکیب چک\u200cها'), ('pos', 'دستگاه POS'), ('cheque_return', 'چک برگشتی'), ('bounced_cheque_return', 'برگشت چک برگشتی')], max_length=30, verbose_name='روش پرداخت'),
        ),
    ]
