# Generated by Django 4.2.11 on 2025-08-20 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0070_add_cheque_return_payment_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialoperation',
            name='operation_type',
            field=models.CharField(choices=[('RECEIVE_FROM_CUSTOMER', 'دریافت از مشتری'), ('PAY_TO_CUSTOMER', 'پرداخت به مشتری'), ('RECEIVE_FROM_BANK', 'دریافت از بانک'), ('PAY_TO_BANK', 'پرداخت به بانک'), ('BANK_TRANSFER', 'حواله بانکی'), ('CASH_WITHDRAWAL', 'برداشت نقدی از بانک'), ('PAYMENT_TO_CASH', 'پرداخت به صندوق'), ('PAYMENT_FROM_CASH', 'پرداخت از صندوق'), ('CAPITAL_INVESTMENT', 'سرمایه گذاری'), ('PETTY_CASH', 'تنخواه'), ('DEPOSIT_TO_BANK', 'واگذاری چک به بانک'), ('CHECK_RESET_FROM_CLEARED', 'بازگشت چک وصول شده به حالت اولیه'), ('CHECK_RESET_FROM_BOUNCED', 'بازگشت چک برگشت خورده به حالت اولیه'), ('CHECK_RESET_FROM_ISSUED', 'بازگشت چک صادر شده به حالت اولیه'), ('PURCHASE_INVOICE', 'فاکتور خرید'), ('SALES_INVOICE', 'فاکتور فروش')], max_length=50, verbose_name='نوع عملیات'),
        ),
        migrations.CreateModel(
            name='ReceivedChequeAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('CREATED', 'ایجاد چک'), ('STATUS_CHANGED', 'تغییر وضعیت'), ('CLEARED', 'وصول چک'), ('BOUNCED', 'برگشت چک'), ('DEPOSITED', 'واگذار به بانک'), ('SPENT', 'خرج چک'), ('RETURNED', 'مسترد چک'), ('MANUALLY_CLEARED', 'وصول دستی'), ('EDITED', 'ویرایش اطلاعات'), ('DELETED', 'حذف چک'), ('RESTORED', 'بازگردانی چک')], max_length=20, verbose_name='نوع عملیات')),
                ('operation_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عملیات')),
                ('old_status', models.CharField(blank=True, choices=[('RECEIVED', 'دریافت شده'), ('DEPOSITED', 'واگذار به بانک'), ('CLEARED', 'وصول شده'), ('MANUALLY_CLEARED', 'وصول به صورت دستی'), ('SPENT', 'خرج شده'), ('BOUNCED', 'برگشت خورده'), ('RETURNED', 'مسترد شده')], max_length=20, null=True, verbose_name='وضعیت قبلی')),
                ('old_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='مبلغ قبلی')),
                ('old_due_date', models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید قبلی')),
                ('old_recipient_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='گیرنده قبلی')),
                ('new_status', models.CharField(blank=True, choices=[('RECEIVED', 'دریافت شده'), ('DEPOSITED', 'واگذار به بانک'), ('CLEARED', 'وصول شده'), ('MANUALLY_CLEARED', 'وصول به صورت دستی'), ('SPENT', 'خرج شده'), ('BOUNCED', 'برگشت خورده'), ('RETURNED', 'مسترد شده')], max_length=20, null=True, verbose_name='وضعیت جدید')),
                ('new_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='مبلغ جدید')),
                ('new_due_date', models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید جدید')),
                ('new_recipient_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='گیرنده جدید')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات عملیات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='products.receivedcheque', verbose_name='چک دریافتی')),
                ('new_deposited_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_deposited_checks_audit', to='products.bankaccount', verbose_name='حساب بانکی واگذار شده جدید')),
                ('old_deposited_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_deposited_checks_audit', to='products.bankaccount', verbose_name='حساب بانکی واگذار شده قبلی')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='انجام دهنده')),
            ],
            options={
                'verbose_name': 'تاریخچه چک دریافتی',
                'verbose_name_plural': 'تاریخچه چک\u200cهای دریافتی',
                'ordering': ['-operation_date'],
                'indexes': [models.Index(fields=['cheque', 'operation_date'], name='products_re_cheque__96157b_idx'), models.Index(fields=['operation', 'operation_date'], name='products_re_operati_afc865_idx'), models.Index(fields=['performed_by', 'operation_date'], name='products_re_perform_7f961b_idx')],
            },
        ),
    ]
