# Generated by Django 4.2.11 on 2025-08-20 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0071_add_received_cheque_audit_trail'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNumberSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_number', models.PositiveIntegerField(default=1, verbose_name='شماره سند فعلی')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='شماره سند بعدی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات شماره\u200cگذاری اسناد',
                'verbose_name_plural': 'تنظیمات شماره\u200cگذاری اسناد',
            },
        ),
        migrations.AlterModelOptions(
            name='documentnumber',
            options={'ordering': ['-document_number'], 'verbose_name': 'شماره سند', 'verbose_name_plural': 'شماره\u200cهای اسناد'},
        ),
        migrations.AlterUniqueTogether(
            name='documentnumber',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='documentnumber',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع محتوا'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentnumber',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentnumber',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AddField(
            model_name='documentnumber',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_documents', to=settings.AUTH_USER_MODEL, verbose_name='حذف کننده'),
        ),
        migrations.AddField(
            model_name='documentnumber',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='documentnumber',
            name='document_number',
            field=models.PositiveIntegerField(default=2, unique=True, verbose_name='شماره سند'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentnumber',
            name='document_type',
            field=models.CharField(choices=[('SALES_INVOICE', 'فاکتور فروش'), ('PURCHASE_INVOICE', 'فاکتور خرید'), ('ORDER', 'سفارش'), ('SHIPMENT', 'حمل و نقل'), ('CHECK_ISSUED', 'چک صادر شده'), ('CHECK_RECEIVED', 'چک دریافتی'), ('FINANCIAL_OPERATION', 'عملیات مالی'), ('FUND_OPERATION', 'عملیات صندوق'), ('PETTY_CASH', 'تنخواه'), ('VOUCHER', 'سند حسابداری'), ('RECEIPT', 'رسید'), ('PAYMENT', 'پرداخت'), ('CUSTOMER_BALANCE', 'تراز مشتری'), ('BANK_TRANSACTION', 'تراکنش بانکی'), ('OTHER', 'سایر')], default=4, max_length=30, verbose_name='نوع سند'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentnumber',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف شده'),
        ),
        migrations.AddField(
            model_name='documentnumber',
            name='object_id',
            field=models.PositiveIntegerField(default=5, verbose_name='شناسه شیء'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='documentnumber',
            index=models.Index(fields=['document_type', 'content_type', 'object_id'], name='products_do_documen_d41f37_idx'),
        ),
        migrations.AddIndex(
            model_name='documentnumber',
            index=models.Index(fields=['document_number'], name='products_do_documen_b357b9_idx'),
        ),
        migrations.AddIndex(
            model_name='documentnumber',
            index=models.Index(fields=['created_at'], name='products_do_created_ec3ed5_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentnumber',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_document_reference'),
        ),
        migrations.AddField(
            model_name='documentnumbersettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بروزرسانی کننده'),
        ),
        migrations.RemoveField(
            model_name='documentnumber',
            name='number',
        ),
        migrations.RemoveField(
            model_name='documentnumber',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='documentnumber',
            name='warehouse',
        ),
    ]
