# Generated by Django 4.2.11 on 2025-08-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0072_add_document_numbering_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='detailed_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات دقیق عملیات'),
        ),
    ]
