# Generated by Django 4.2.11 on 2025-08-20 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0073_add_detailed_description_to_voucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='detailed_description',
        ),
    ]
