# Generated by Django 4.2.11 on 2025-08-20 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0074_remove_detailed_description_from_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedcheque',
            name='recipient_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_cheques_as_recipient', to='products.customer', verbose_name='مشتری گیرنده چک'),
        ),
    ]
