# Generated by Django 4.2.11 on 2025-08-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0075_add_recipient_customer_to_received_cheque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialoperation',
            name='operation_type',
            field=models.CharField(choices=[('RECEIVE_FROM_CUSTOMER', 'دریافت از مشتری'), ('PAY_TO_CUSTOMER', 'پرداخت به مشتری'), ('RECEIVE_FROM_BANK', 'دریافت از بانک'), ('PAY_TO_BANK', 'پرداخت به بانک'), ('BANK_TRANSFER', 'حواله بانکی'), ('CASH_WITHDRAWAL', 'برداشت نقدی از بانک'), ('PAYMENT_TO_CASH', 'پرداخت به صندوق'), ('PAYMENT_FROM_CASH', 'پرداخت از صندوق'), ('CAPITAL_INVESTMENT', 'سرمایه گذاری'), ('PETTY_CASH', 'تنخواه'), ('DEPOSIT_TO_BANK', 'واگذاری چک به بانک'), ('CHECK_RESET_FROM_CLEARED', 'بازگشت چک وصول شده به حالت اولیه'), ('CHECK_RESET_FROM_BOUNCED', 'بازگشت چک برگشت خورده به حالت اولیه'), ('CHECK_RESET_FROM_ISSUED', 'بازگشت چک صادر شده به حالت اولیه'), ('CHECK_BOUNCE', 'برگشت چک دریافتی'), ('ISSUED_CHECK_BOUNCE', 'برگشت چک صادر شده'), ('PURCHASE_INVOICE', 'فاکتور خرید'), ('SALES_INVOICE', 'فاکتور فروش')], max_length=50, verbose_name='نوع عملیات'),
        ),
        migrations.AlterField(
            model_name='financialoperation',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدی'), ('bank_transfer', 'حواله بانکی'), ('cheque', 'چک'), ('spend_cheque', 'خرج چک'), ('mixed_cheque', 'ترکیب چک\u200cها'), ('pos', 'دستگاه POS'), ('cheque_return', 'چک برگشتی'), ('bounced_cheque_return', 'برگشت چک برگشتی'), ('cheque_bounce', 'برگشت چک دریافتی')], max_length=30, verbose_name='روش پرداخت'),
        ),
    ]
